---
delegatebot:
  watch:
  - target: { channel: &pcf-windows-eng G0GQ8KXLZ }
  delegate:
    union:
    - user: { id: &Garima_Sharma U2LAQS9RQ }
    - user: { id: &Simon_Jones U0H6HC71B }
    - user: { id: &George_Gelashvili U0FA4167Q }
    - user: { id: &Matthew_Horan U0563PD3X }
    - user: { id: &Jackson_Feeny U7U1BRTR8 }
    - user: { id: &Kartik_Lunkad U0MJ7N77U }
    - user: { id: &Tal_Usvyatsky UL5DFJS4C }
    - user: { id: &Daniel_Basner UJRBWR9FE }
    - user: { id: &Anushka_Makhija U5C7QJGDA }
