---
delegatebot:
  watch:
  - target: { channel: &pcf-windows-eng G0GQ8KXLZ }
  delegate:
    union:
    - user: { id: &George_Gelashvili U0FA4167Q }
    - user: { id: &Matthew_Horan U0563PD3X }
    - user: { id: &Tal_Usvyatsky UL5DFJS4C }
    - user: { id: &Daniel_Basner UJRBWR9FE }
    - user: { id: &Anushka_Makhija U5C7QJGDA }
    - user: { id: &Frankie_GJ UMVSQF1UZ }
    - user: { id: &Sam_Coward U07CBKZU4 }
    - user: { id: &Austina_Lin US9KEFEDC }
