---
delegatebot:
  watch:
  - target: { channel: &pcf-windows-eng G0GQ8KXLZ }
  delegate:
    union:
    - user: { id: &Yechiel UDT3Q8KLH }
    - user: { id: &Arjun UBKBNQBBM }
    - user: { id: &Matt U0563PD3X }
    - user: { id: &Genevieve U0BSZH3EX }
    - user: { id: &Cara UK06QV0BU }
    - user: { id: &Jack U7U1BRTR8 }
